"""create meals and meal_items tables

Revision ID: 092cbe7f6fec
Revises: 452b73097c65
Create Date: 2026-10-06 02:12:34.949907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '092cbe7f6fec'
down_revision: Union[str, Sequence[str], None] = '452b73097c65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.String(length=50), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meals_consumed_at'), 'meals', ['consumed_at'], unique=False)
    op.create_index(op.f('ix_meals_id'), 'meals', ['id'], unique=False)
    op.create_index('ix_meals_user_consumed', 'meals', ['user_id', 'consumed_at'], unique=False)
    op.create_index(op.f('ix_meals_user_id'), 'meals', ['user_id'], unique=False)
    op.create_table('meal_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('food_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('calculated_calories', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('calculated_protein', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('calculated_carbohydrates', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('calculated_fat', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('calculated_fiber', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('calculated_calories >= 0', name='chk_meal_item_calories_non_negative'),
    sa.CheckConstraint('calculated_carbohydrates >= 0', name='chk_meal_item_carbs_non_negative'),
    sa.CheckConstraint('calculated_fat >= 0', name='chk_meal_item_fat_non_negative'),
    sa.CheckConstraint('calculated_fiber >= 0', name='chk_meal_item_fiber_non_negative'),
    sa.CheckConstraint('calculated_protein >= 0', name='chk_meal_item_protein_non_negative'),
    sa.CheckConstraint('quantity > 0', name='chk_meal_item_quantity_positive'),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_items_food_item_id'), 'meal_items', ['food_item_id'], unique=False)
    op.create_index(op.f('ix_meal_items_id'), 'meal_items', ['id'], unique=False)
    op.create_index(op.f('ix_meal_items_meal_id'), 'meal_items', ['meal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meal_items_meal_id'), table_name='meal_items')
    op.drop_index(op.f('ix_meal_items_id'), table_name='meal_items')
    op.drop_index(op.f('ix_meal_items_food_item_id'), table_name='meal_items')
    op.drop_table('meal_items')
    op.drop_index(op.f('ix_meals_user_id'), table_name='meals')
    op.drop_index('ix_meals_user_consumed', table_name='meals')
    op.drop_index(op.f('ix_meals_id'), table_name='meals')
    op.drop_index(op.f('ix_meals_consumed_at'), table_name='meals')
    op.drop_table('meals')
    # ### end Alembic commands ###
