"""create food_items table

Revision ID: 452b73097c65
Revises: 85d04c028d5e
Create Date: 2026-10-06 02:06:37.584856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '452b73097c65'
down_revision: Union[str, Sequence[str], None] = '85d04c028d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('serving_size', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('serving_unit', sa.String(length=50), nullable=False),
    sa.Column('calories', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('protein', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('carbohydrates', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('fat', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('fiber', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('calories >= 0', name='chk_food_calories_non_negative'),
    sa.CheckConstraint('carbohydrates >= 0', name='chk_food_carbohydrates_non_negative'),
    sa.CheckConstraint('fat >= 0', name='chk_food_fat_non_negative'),
    sa.CheckConstraint('fiber >= 0', name='chk_food_fiber_non_negative'),
    sa.CheckConstraint('protein >= 0', name='chk_food_protein_non_negative'),
    sa.CheckConstraint('serving_size > 0', name='chk_food_serving_size_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_items_id'), 'food_items', ['id'], unique=False)
    op.create_index(op.f('ix_food_items_name'), 'food_items', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_items_name'), table_name='food_items')
    op.drop_index(op.f('ix_food_items_id'), table_name='food_items')
    op.drop_table('food_items')
    # ### end Alembic commands ###
