"""
Pydantic schemas for the agent chat API endpoint.
"""

from typing import List
from pydantic import BaseModel, Field


class AgentChatRequest(BaseModel):
    """User input message to the agent."""
    message: str = Field(..., min_length=1, max_length=1000, description="User natural language message or query")


class AgentChatResponse(BaseModel):
    """Agent response containing synthesized answer and tools invoked."""
    response: str = Field(..., description="Final natural language response generated by the agent")
    tools_used: List[str] = Field(default_factory=list, description="List of tools invoked during reasoning")
