"""
Pydantic schemas for the agent chat API endpoint.
"""

from typing import List, Optional
from pydantic import BaseModel, Field


class AgentChatRequest(BaseModel):
    """User input message to the agent."""
    message: str = Field(..., min_length=1, max_length=1000, description="User natural language message or query")


class AgentChatResponse(BaseModel):
    """Agent response containing synthesized answer, tools invoked, and execution metrics."""
    response: str = Field(..., description="Final natural language response generated by the agent")
    tools_used: List[str] = Field(default_factory=list, description="List of tools invoked during reasoning")
    duration_seconds: Optional[float] = Field(default=None, description="Total execution latency in seconds")
    iterations: Optional[int] = Field(default=None, description="Number of agent reasoning iterations executed")

